[package]
name = "evm-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
bytes = "1.4.0"
exitcode = "1.1.2"
getopts = "0.2.21"
maplit = "1.0.2"
